package tv.wfc.livestreamsales.viewmodels.broadcastsinformation

import tv.wfc.livestreamsales.viewmodels.base.IToBePreparedViewModel

interface IBroadcastsInformationViewModel: IToBePreparedViewModel